[project]
name = "lclstreamer-api-usage-example"
version = "0.1.0"
description = "An example of how to use the lclstreamer-api-client library"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic-settings>=2.6.0",
    "pyzmq>=27.1.0",
    "lclstream-api-client @ git+https://github.com/lclstream/lclstream_api.git@add-jobspec-override#subdirectory=client/"
]
