"""add cache_mode to transfers

Revision ID: aa298396d6a0
Revises: 6ead17ed69da
Create Date: 2026-07-10 14:32:52.500790

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa298396d6a0"
down_revision: str | list[str] | None = "6ead17ed69da"
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfers",
        sa.Column(
            "cache_mode", sa.String(), server_default="per_transfer", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfers", "cache_mode")
    # ### end Alembic commands ###
