"""add job_spec to transfers

Revision ID: f3a1c9b8e2d4
Revises: 0236c97ae695
Create Date: 2026-07-13 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a1c9b8e2d4"
down_revision: str | list[str] | None = "0236c97ae695"
branch_labels: str | list[str] | None = None
depends_on: str | list[str] | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfers",
        sa.Column("job_spec", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfers", "job_spec")
    # ### end Alembic commands ###
