// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { CachesService, type Options, TransfersService } from '../sdk.gen';
import type { CancelTransferTransfersTransferIdDeleteData, CancelTransferTransfersTransferIdDeleteError, CancelTransferTransfersTransferIdDeleteResponse, GetCachesCachesGetData, GetCachesCachesGetError, GetCachesCachesGetResponse, GetTransferLogsTransfersTransferIdLogsGetData, GetTransferLogsTransfersTransferIdLogsGetError, GetTransferLogsTransfersTransferIdLogsGetResponse, GetTransferLogTransfersTransferIdLogsStreamGetData, GetTransferLogTransfersTransferIdLogsStreamGetError, GetTransferLogTransfersTransferIdLogsStreamGetResponse, GetTransfersTransfersGetData, GetTransfersTransfersGetError, GetTransfersTransfersGetResponse, GetTransferTransfersTransferIdGetData, GetTransferTransfersTransferIdGetError, GetTransferTransfersTransferIdGetResponse, NewTransferTransfersPostData, NewTransferTransfersPostError, NewTransferTransfersPostResponse, ShutdownCacheCachesCacheIdDeleteData, ShutdownCacheCachesCacheIdDeleteError, ShutdownCacheCachesCacheIdDeleteResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCachesCachesGetQueryKey = (options: Options<GetCachesCachesGetData>) => createQueryKey('getCachesCachesGet', options);

/**
 * Get Caches
 */
export const getCachesCachesGetOptions = (options: Options<GetCachesCachesGetData>) => queryOptions<GetCachesCachesGetResponse, AxiosError<GetCachesCachesGetError>, GetCachesCachesGetResponse, ReturnType<typeof getCachesCachesGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await CachesService.getCachesCachesGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCachesCachesGetQueryKey(options)
});

/**
 * Shutdown Cache
 */
export const shutdownCacheCachesCacheIdDeleteMutation = (options?: Partial<Options<ShutdownCacheCachesCacheIdDeleteData>>): UseMutationOptions<ShutdownCacheCachesCacheIdDeleteResponse, AxiosError<ShutdownCacheCachesCacheIdDeleteError>, Options<ShutdownCacheCachesCacheIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<ShutdownCacheCachesCacheIdDeleteResponse, AxiosError<ShutdownCacheCachesCacheIdDeleteError>, Options<ShutdownCacheCachesCacheIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await CachesService.shutdownCacheCachesCacheIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTransfersTransfersGetQueryKey = (options?: Options<GetTransfersTransfersGetData>) => createQueryKey('getTransfersTransfersGet', options);

/**
 * Get Transfers
 */
export const getTransfersTransfersGetOptions = (options?: Options<GetTransfersTransfersGetData>) => queryOptions<GetTransfersTransfersGetResponse, AxiosError<GetTransfersTransfersGetError>, GetTransfersTransfersGetResponse, ReturnType<typeof getTransfersTransfersGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await TransfersService.getTransfersTransfersGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransfersTransfersGetQueryKey(options)
});

/**
 * New Transfer
 */
export const newTransferTransfersPostMutation = (options?: Partial<Options<NewTransferTransfersPostData>>): UseMutationOptions<NewTransferTransfersPostResponse, AxiosError<NewTransferTransfersPostError>, Options<NewTransferTransfersPostData>> => {
    const mutationOptions: UseMutationOptions<NewTransferTransfersPostResponse, AxiosError<NewTransferTransfersPostError>, Options<NewTransferTransfersPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await TransfersService.newTransferTransfersPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Cancel Transfer
 */
export const cancelTransferTransfersTransferIdDeleteMutation = (options?: Partial<Options<CancelTransferTransfersTransferIdDeleteData>>): UseMutationOptions<CancelTransferTransfersTransferIdDeleteResponse, AxiosError<CancelTransferTransfersTransferIdDeleteError>, Options<CancelTransferTransfersTransferIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<CancelTransferTransfersTransferIdDeleteResponse, AxiosError<CancelTransferTransfersTransferIdDeleteError>, Options<CancelTransferTransfersTransferIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await TransfersService.cancelTransferTransfersTransferIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTransferTransfersTransferIdGetQueryKey = (options: Options<GetTransferTransfersTransferIdGetData>) => createQueryKey('getTransferTransfersTransferIdGet', options);

/**
 * Get Transfer
 */
export const getTransferTransfersTransferIdGetOptions = (options: Options<GetTransferTransfersTransferIdGetData>) => queryOptions<GetTransferTransfersTransferIdGetResponse, AxiosError<GetTransferTransfersTransferIdGetError>, GetTransferTransfersTransferIdGetResponse, ReturnType<typeof getTransferTransfersTransferIdGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await TransfersService.getTransferTransfersTransferIdGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransferTransfersTransferIdGetQueryKey(options)
});

export const getTransferLogsTransfersTransferIdLogsGetQueryKey = (options: Options<GetTransferLogsTransfersTransferIdLogsGetData>) => createQueryKey('getTransferLogsTransfersTransferIdLogsGet', options);

/**
 * Get Transfer Logs
 */
export const getTransferLogsTransfersTransferIdLogsGetOptions = (options: Options<GetTransferLogsTransfersTransferIdLogsGetData>) => queryOptions<GetTransferLogsTransfersTransferIdLogsGetResponse, AxiosError<GetTransferLogsTransfersTransferIdLogsGetError>, GetTransferLogsTransfersTransferIdLogsGetResponse, ReturnType<typeof getTransferLogsTransfersTransferIdLogsGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await TransfersService.getTransferLogsTransfersTransferIdLogsGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransferLogsTransfersTransferIdLogsGetQueryKey(options)
});

export const getTransferLogTransfersTransferIdLogsStreamGetQueryKey = (options: Options<GetTransferLogTransfersTransferIdLogsStreamGetData>) => createQueryKey('getTransferLogTransfersTransferIdLogsStreamGet', options);

/**
 * Get Transfer Log
 */
export const getTransferLogTransfersTransferIdLogsStreamGetOptions = (options: Options<GetTransferLogTransfersTransferIdLogsStreamGetData>) => queryOptions<GetTransferLogTransfersTransferIdLogsStreamGetResponse, AxiosError<GetTransferLogTransfersTransferIdLogsStreamGetError>, GetTransferLogTransfersTransferIdLogsStreamGetResponse, ReturnType<typeof getTransferLogTransfersTransferIdLogsStreamGetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await TransfersService.getTransferLogTransfersTransferIdLogsStreamGet({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTransferLogTransfersTransferIdLogsStreamGetQueryKey(options)
});
