// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelTransferTransfersTransferIdDeleteData, CancelTransferTransfersTransferIdDeleteErrors, CancelTransferTransfersTransferIdDeleteResponses, GetTransferLogsTransfersTransferIdLogsGetData, GetTransferLogsTransfersTransferIdLogsGetErrors, GetTransferLogsTransfersTransferIdLogsGetResponses, GetTransferLogTransfersTransferIdLogsStreamGetData, GetTransferLogTransfersTransferIdLogsStreamGetErrors, GetTransferLogTransfersTransferIdLogsStreamGetResponses, GetTransfersTransfersGetData, GetTransfersTransfersGetErrors, GetTransfersTransfersGetResponses, GetTransferTransfersTransferIdGetData, GetTransferTransfersTransferIdGetErrors, GetTransferTransfersTransferIdGetResponses, NewTransferTransfersPostData, NewTransferTransfersPostErrors, NewTransferTransfersPostResponses } from './types.gen';
import { zCancelTransferTransfersTransferIdDeleteResponse, zGetTransferLogsTransfersTransferIdLogsGetResponse, zGetTransferLogTransfersTransferIdLogsStreamGetResponse, zGetTransfersTransfersGetResponse, zGetTransferTransfersTransferIdGetResponse, zNewTransferTransfersPostResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class TransfersService {
    /**
     * Get Transfers
     */
    public static getTransfersTransfersGet<ThrowOnError extends boolean = false>(options?: Options<GetTransfersTransfersGetData, ThrowOnError>) {
        return (options?.client ?? client).get<GetTransfersTransfersGetResponses, GetTransfersTransfersGetErrors, ThrowOnError>({
            responseType: 'json',
            responseValidator: async (data) => await zGetTransfersTransfersGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/',
            ...options
        });
    }
    
    /**
     * New Transfer
     */
    public static newTransferTransfersPost<ThrowOnError extends boolean = false>(options: Options<NewTransferTransfersPostData, ThrowOnError>) {
        return (options.client ?? client).post<NewTransferTransfersPostResponses, NewTransferTransfersPostErrors, ThrowOnError>({
            responseType: 'json',
            responseValidator: async (data) => await zNewTransferTransfersPostResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Cancel Transfer
     */
    public static cancelTransferTransfersTransferIdDelete<ThrowOnError extends boolean = false>(options: Options<CancelTransferTransfersTransferIdDeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<CancelTransferTransfersTransferIdDeleteResponses, CancelTransferTransfersTransferIdDeleteErrors, ThrowOnError>({
            responseType: 'json',
            responseValidator: async (data) => await zCancelTransferTransfersTransferIdDeleteResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/{transfer_id}',
            ...options
        });
    }
    
    /**
     * Get Transfer
     */
    public static getTransferTransfersTransferIdGet<ThrowOnError extends boolean = false>(options: Options<GetTransferTransfersTransferIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetTransferTransfersTransferIdGetResponses, GetTransferTransfersTransferIdGetErrors, ThrowOnError>({
            responseType: 'json',
            responseValidator: async (data) => await zGetTransferTransfersTransferIdGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/{transfer_id}',
            ...options
        });
    }
    
    /**
     * Get Transfer Logs
     */
    public static getTransferLogsTransfersTransferIdLogsGet<ThrowOnError extends boolean = false>(options: Options<GetTransferLogsTransfersTransferIdLogsGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetTransferLogsTransfersTransferIdLogsGetResponses, GetTransferLogsTransfersTransferIdLogsGetErrors, ThrowOnError>({
            responseType: 'json',
            responseValidator: async (data) => await zGetTransferLogsTransfersTransferIdLogsGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/{transfer_id}/logs',
            ...options
        });
    }
    
    /**
     * Get Transfer Log
     */
    public static getTransferLogTransfersTransferIdLogsStreamGet<ThrowOnError extends boolean = false>(options: Options<GetTransferLogTransfersTransferIdLogsStreamGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetTransferLogTransfersTransferIdLogsStreamGetResponses, GetTransferLogTransfersTransferIdLogsStreamGetErrors, ThrowOnError>({
            responseType: 'text',
            responseValidator: async (data) => await zGetTransferLogTransfersTransferIdLogsStreamGetResponse.parseAsync(data),
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/transfers/{transfer_id}/logs/{stream}',
            ...options
        });
    }
}
