// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * BatchProcessingPipelineParameters
 *
 * Configuration parameters for the Batch Processing Pipeline
 *
 * This pipeline accumulates individual events into fixed-size batches before
 * passing them downstream
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BatchProcessingPipeline"``
 *
 * batch_size: Number of events to accumulate per batch
 */
export type BatchProcessingPipelineParameters = {
    /**
     * Batch Size
     */
    batch_size: number;
    /**
     * Type
     */
    type: 'BatchProcessingPipeline';
};

/**
 * BinaryDataStreamingDataHandlerParameters
 *
 * Configuration parameters for the Binary Data Streaming Data Handler
 *
 * This data handler forwards serialized byte objects to one or more remote
 * endpoints over a ZMQ PUSH socket
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BinaryDataStreamingDataHandler"``
 *
 * urls: List of endpoint URLs to bind to (server mode) or connect to
 * (client mode)
 *
 * distribute: Boolean, if True: round robin connect the ranks, False: all ranks connect to all urls and send the same data
 *
 * buffer: buffer size, if set to 0 the OS default is used
 *
 * role: Whether this node acts as the ZMQ ``"server"`` (binds) or
 * ``"client"`` (connects). Defaults to ``"server"``
 *
 * library: Underlying transport library to use. Currently only ``"zmq"``
 * is supported. Defaults to ``"zmq"``
 *
 * socket_type: Socket pattern to use. Currently only ``"push"`` is
 * supported. Defaults to ``"push"``
 */
export type BinaryDataStreamingDataHandlerParameters = {
    /**
     * Buffer
     */
    buffer?: number;
    /**
     * Distribute
     */
    distribute?: boolean;
    /**
     * Library
     */
    library?: 'zmq';
    /**
     * Role
     */
    role?: 'server' | 'client';
    /**
     * Socket Type
     */
    socket_type?: 'push';
    /**
     * Type
     */
    type: 'BinaryDataStreamingDataHandler';
    /**
     * Urls
     */
    urls: Array<string>;
};

/**
 * BinaryFileWritingDataHandlerParameters
 *
 * Configuration parameters for the Binary File Writing Data Handler
 *
 * This data handler writes each serialized byte object to a separate file on
 * the filesystem
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BinaryFileWritingDataHandler"``
 *
 * file_prefix: Optional string prepended to every output filename,
 * separated from the rest of the name by an underscore. Defaults to
 * ``""`` (no prefix)
 *
 * file_suffix: File extension used for output files, without the leading
 * dot. Defaults to ``"h5"``
 *
 * write_directory: Directory in which output files are created. The
 * directory is created (including parents) if it does not already
 * exist. Defaults to the current working directory
 */
export type BinaryFileWritingDataHandlerParameters = {
    /**
     * File Prefix
     */
    file_prefix?: string;
    /**
     * File Suffix
     */
    file_suffix?: string;
    /**
     * Type
     */
    type: 'BinaryFileWritingDataHandler';
    /**
     * Write Directory
     */
    write_directory?: string;
};

/**
 * CacheMode
 */
export type CacheMode = 'per_transfer' | 'shared';

/**
 * CacheShutdownConflict
 */
export type CacheShutdownConflict = {
    /**
     * Active Transfer Count
     */
    active_transfer_count: number;
    /**
     * Message
     */
    message: string;
};

/**
 * CacheState
 *
 * Observed fastcache cache lifecycle.
 */
export type CacheState = 'new' | 'queued' | 'active' | 'completed' | 'failed' | 'canceled';

/**
 * CacheStatusPublic
 */
export type CacheStatusPublic = {
    /**
     * Id
     */
    id: string;
    state: CacheState;
};

/**
 * CachesPublic
 */
export type CachesPublic = {
    /**
     * Data
     */
    data: Array<CacheStatusPublic>;
};

/**
 * ConstValueParameters
 *
 * Parameters for ConstValue class
 */
export type ConstValueParameters = {
    /**
     * Dtype
     */
    dtype: string;
    /**
     * Type
     */
    type: 'ConstValue';
    /**
     * Value
     */
    value: number | number | Array<number | number>;
};

/**
 * ConsumerConnectionInfo
 *
 * The cache push socket the consumer connects to.
 */
export type ConsumerConnectionInfo = {
    /**
     * Host
     */
    host: string;
    /**
     * Port
     */
    port: number;
    /**
     * Uri
     */
    uri: string;
};

/**
 * Container
 *
 * Represents a container specification for job execution.  Implementation notes: The value of gpu_cores_per_process in ResourceSpec should be used to determine if the container should be run with GPU support. Likewise, the value of launcher in JobSpec should be used to determine if the container should be run with MPI support. The container should by default. be run with host networking.
 */
export type Container = {
    /**
     * Additional Properties
     */
    additional_properties?: {
        [key: string]: unknown;
    };
    /**
     * Image
     *
     * The container image to use (e.g., 'docker.io/library/ubuntu:latest')
     */
    image: string;
    /**
     * Volume Mounts
     *
     * List of volume mounts for the container
     */
    volume_mounts?: Array<VolumeMount> | null;
};

/**
 * GenericRandomNumpyArrayParameters
 *
 * Parameters for the GenericRandomNumpyArray class
 */
export type GenericRandomNumpyArrayParameters = {
    /**
     * Always Random
     */
    always_random?: boolean;
    /**
     * Array Dtype
     */
    array_dtype: string;
    /**
     * Array Shape
     */
    array_shape: number | Array<number>;
    /**
     * Type
     */
    type: 'GenericRandomNumpyArray';
};

/**
 * HDF5BinarySerializerParameters
 *
 * Configuration parameters for the HDF5 binary serializer
 *
 * This serializer encodes a batch of event data arrays into an in-memory
 * HDF5 file. Optional compression can be applied to each dataset
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"HDF5BinarySerializer"``
 *
 * compression_level: Compression level passed to the chosen algorithm.
 * Interpretation depends on the algorithm. Defaults to ``3``
 *
 * compression: Compression algorithm to use. Supported values are
 * ``"gzip"``, ``"gzip_with_shuffle"``, ``"bitshuffle_with_lz4"``,
 * ``"bitshuffle_with_zstd"``, and ``"zfp"``. Set to ``None`` to
 * disable compression. Defaults to ``None``
 *
 * fields: Dictionary storing the mapping from data source name to the
 * HDF5 dataset path under which that source's data will be stored
 */
export type Hdf5BinarySerializerParameters = {
    /**
     * Compression
     */
    compression?: 'gzip' | 'gzip_with_shuffle' | 'bitshuffle_with_lz4' | 'bitshuffle_with_zstd' | 'zfp' | null;
    /**
     * Compression Level
     */
    compression_level?: number;
    /**
     * Fields
     */
    fields: {
        [key: string]: string;
    };
    /**
     * Type
     */
    type: 'HDF5BinarySerializer';
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InsufficientTokenLifetimeError
 */
export type InsufficientTokenLifetimeError = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Remaining Seconds
     */
    remaining_seconds: number;
    /**
     * Required Seconds
     */
    required_seconds: number;
};

/**
 * InternalEventSourceParameters
 *
 * Configuration parameters for the Internal Event Source
 *
 * This event source generates synthetic events entirely in-process and does
 * not depend on any external data-acquisition framework. It is intended
 * mainly for testing and development
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"InternalEventSource"``
 *
 * number_of_events_to_generate: Total number of synthetic events to
 * produce before the source is exhausted
 */
export type InternalEventSourceParameters = {
    /**
     * Number Of Events To Generate
     */
    number_of_events_to_generate: number;
    /**
     * Type
     */
    type: 'InternalEventSource';
    [key: string]: unknown;
};

/**
 * JobAttributes
 *
 * Additional attributes and scheduling parameters for a job.
 */
export type JobAttributes = {
    /**
     * Account
     *
     * Account or project to charge for resource usage
     */
    account?: string | null;
    /**
     * Additional Properties
     */
    additional_properties?: {
        [key: string]: unknown;
    };
    /**
     * Custom Attributes
     *
     * Custom scheduler-specific attributes as key-value pairs
     */
    custom_attributes?: {
        [key: string]: string;
    } | null;
    /**
     * Duration
     *
     * Duration in seconds
     */
    duration?: number | null;
    /**
     * Queue Name
     *
     * Name of the queue or partition to submit the job to
     */
    queue_name?: string | null;
    /**
     * Reservation Id
     *
     * ID of a reservation to use for the job
     */
    reservation_id?: string | null;
};

/**
 * JobSpec
 *
 * Specification for a job.
 */
export type JobSpec = {
    /**
     * Arguments
     *
     * Command-line arguments to pass to the executable or container
     */
    arguments?: Array<string> | null;
    /**
     * Additional job attributes such as duration, queue, and account
     */
    attributes?: JobAttributes | null;
    /**
     * Container specification for containerized execution
     */
    container?: Container | null;
    /**
     * Directory
     *
     * Working directory for the job
     */
    directory?: string | null;
    /**
     * Environment
     *
     * Environment variables to set for the job. If container is specified, these will be set inside the container.
     */
    environment?: {
        [key: string]: string;
    } | null;
    /**
     * Executable
     *
     * Path to the executable to run. If container is specified, this will be used as the entrypoint to the container.
     */
    executable?: string | null;
    /**
     * Inherit Environment
     *
     * Whether to inherit the environment variables from the submission environment
     */
    inherit_environment?: boolean | null;
    /**
     * Launcher
     *
     * Job launcher to use (e.g., 'mpirun', 'srun')
     */
    launcher?: string | null;
    /**
     * Name
     *
     * Name of the job
     */
    name?: string | null;
    /**
     * Post Launch
     *
     * Script or commands to run after the job completes
     */
    post_launch?: string | null;
    /**
     * Pre Launch
     *
     * Script or commands to run before launching the job
     */
    pre_launch?: string | null;
    /**
     * Resource requirements for the job
     */
    resources?: ResourceSpec | null;
    /**
     * Stderr Path
     *
     * Path to file to write standard error
     */
    stderr_path?: string | null;
    /**
     * Stdin Path
     *
     * Path to file to use as standard input
     */
    stdin_path?: string | null;
    /**
     * Stdout Path
     *
     * Path to file to write standard output
     */
    stdout_path?: string | null;
};

/**
 * LogReadMode
 */
export type LogReadMode = 'head' | 'tail';

/**
 * LogStream
 */
export type LogStream = 'cache' | 'producer_stdout' | 'producer_stderr';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * Parameters
 *
 * Top-level configuration parameters for an lclstreamer run
 *
 * This model aggregates all sub-component configuration into a single object
 *
 * Attributes:
 *
 * source_identifier: A string that uniquely identifies the data source
 * (e.g. a psana data source string)
 *
 * skip_incomplete_events: When ``True``, events for which one or more
 * data sources returned no data are silently dropped from the stream
 *
 * event_source: Configuration for the event source
 *
 * data_sources: Mapping from arbitrary data source names to the
 * configuration parameters of each data source
 *
 * processing_pipeline: Configuration for the Processing Pipeline applied
 * to the event stream
 *
 * data_serializer: Configuration for the serializer that converts
 * processed events into byte objects
 *
 * data_handlers: Ordered list of data handler configurations; each
 * handler receives the serialized byte object in turn
 */
export type Parameters = {
    /**
     * Data Handlers
     */
    data_handlers: Array<({
        type: 'BinaryDataStreamingDataHandler';
    } & BinaryDataStreamingDataHandlerParameters) | ({
        type: 'BinaryFileWritingDataHandler';
    } & BinaryFileWritingDataHandlerParameters)>;
    /**
     * Data Serializer
     */
    data_serializer: ({
        type: 'HDF5BinarySerializer';
    } & Hdf5BinarySerializerParameters) | ({
        type: 'SimplonBinarySerializer';
    } & SimplonBinarySerializerParameters);
    /**
     * Data Sources
     */
    data_sources: {
        [key: string]: ({
            type: 'GenericRandomNumpyArray';
        } & GenericRandomNumpyArrayParameters) | ({
            type: 'ConstValue';
        } & ConstValueParameters) | ({
            type: 'Psana1DetectorInterface';
        } & Psana1DetectorInterfaceParameters) | ({
            type: 'Psana2DetectorInterface';
        } & Psana2DetectorInterfaceParameters) | ({
            type: 'Psana1Timestamp';
        } & Psana1TimestampParameters) | ({
            type: 'Psana2Timestamp';
        } & Psana2TimestampParameters) | ({
            type: 'SourceIdentifier';
        } & SourceIdentifierParameters) | ({
            type: 'Psana2RunInfo';
        } & Psana2RunInfoParameters);
    };
    /**
     * Event Source
     */
    event_source: ({
        type: 'InternalEventSource';
    } & InternalEventSourceParameters) | ({
        type: 'Psana1EventSource';
    } & Psana1EventSourceParameters) | ({
        type: 'Psana2EventSource';
    } & Psana2EventSourceParameters);
    /**
     * Processing Pipeline
     */
    processing_pipeline: ({
        type: 'BatchProcessingPipeline';
    } & BatchProcessingPipelineParameters) | ({
        type: 'PeaknetPreprocessingPipeline';
    } & PeaknetPreprocessingPipelineParameters);
    /**
     * Skip Incomplete Events
     */
    skip_incomplete_events: boolean;
    /**
     * Source Identifier
     */
    source_identifier: string;
};

/**
 * PeaknetPreprocessingPipelineParameters
 *
 * Configuration parameters for the PeakNet Preprocessing Pipeline
 *
 * This pipeline pads detector images to a uniform size, accumulates them
 * into batches, and optionally adds a channel dimension, preparing the data
 * for inference with the PeakNet model
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"PeaknetPreprocessingPipeline"``
 *
 * batch_size: Number of events to accumulate per batch
 *
 * target_height: Target image height (in pixels) after padding
 *
 * target_width: Target image width (in pixels) after padding
 *
 * pad_style: How to distribute padding around the image; either
 * ``"center"`` (equal padding on both sides) or ``"bottom-right"``
 * (padding added only to the bottom and right edges)
 * Defaults to ``"center"``
 *
 * add_channel_dim: Whether to insert a channel dimension after batching,
 * converting (B, H, W) arrays to (B, C, H, W). Defaults to ``True``
 *
 * num_channels: Number of channels to produce when ``add_channel_dim``
 * is ``True``. Defaults to ``1``
 */
export type PeaknetPreprocessingPipelineParameters = {
    /**
     * Add Channel Dim
     */
    add_channel_dim?: boolean;
    /**
     * Batch Size
     */
    batch_size: number;
    /**
     * Num Channels
     */
    num_channels?: number;
    /**
     * Pad Style
     */
    pad_style?: 'center' | 'bottom-right';
    /**
     * Target Height
     */
    target_height: number;
    /**
     * Target Width
     */
    target_width: number;
    /**
     * Type
     */
    type: 'PeaknetPreprocessingPipeline';
};

/**
 * Psana1DetectorInterfaceParameters
 */
export type Psana1DetectorInterfaceParameters = {
    /**
     * Psana Fields
     */
    psana_fields?: Array<string> | string | null;
    /**
     * Psana Name
     */
    psana_name: string;
    /**
     * Type
     */
    type: 'Psana1DetectorInterface';
};

/**
 * Psana1EventSourceParameters
 *
 * Configuration parameters for the Psana1 Event Source
 *
 * This event source reads events using the psana1 framework (LCLS-I)
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"Psana1EventSource"``
 */
export type Psana1EventSourceParameters = {
    /**
     * Type
     */
    type: 'Psana1EventSource';
};

/**
 * Psana1TimestampParameters
 *
 * Parameters for psana1 timestamp interface
 */
export type Psana1TimestampParameters = {
    /**
     * Type
     */
    type: 'Psana1Timestamp';
};

/**
 * Psana2DetectorInterfaceParameters
 */
export type Psana2DetectorInterfaceParameters = {
    /**
     * Dtype
     */
    dtype?: string | null;
    /**
     * Psana Fields
     */
    psana_fields?: Array<string> | string | null;
    /**
     * Psana Name
     */
    psana_name: string;
    /**
     * Type
     */
    type: 'Psana2DetectorInterface';
};

/**
 * Psana2EventSourceParameters
 *
 * Configuration parameters for the Psana2 Event Source
 *
 * This event source reads events using the psana2 framework (LCLS-II)
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"Psana2EventSource"``
 */
export type Psana2EventSourceParameters = {
    /**
     * Type
     */
    type: 'Psana2EventSource';
};

/**
 * Psana2RunInfoParameters
 *
 * Parameters for run info data source interface
 */
export type Psana2RunInfoParameters = {
    /**
     * Type
     */
    type: 'Psana2RunInfo';
};

/**
 * Psana2TimestampParameters
 *
 * Parameters for psana2 timestamp interface
 */
export type Psana2TimestampParameters = {
    /**
     * Type
     */
    type: 'Psana2Timestamp';
};

/**
 * ResourceSpec
 *
 * Specification of computational resources required for a job.
 */
export type ResourceSpec = {
    /**
     * Additional Properties
     */
    additional_properties?: {
        [key: string]: unknown;
    };
    /**
     * Cpu Cores Per Process
     *
     * Number of CPU cores to allocate per process
     */
    cpu_cores_per_process?: number | null;
    /**
     * Exclusive Node Use
     *
     * Whether to request exclusive use of allocated nodes
     */
    exclusive_node_use?: boolean | null;
    /**
     * Gpu Cores Per Process
     *
     * Number of GPU cores to allocate per process
     */
    gpu_cores_per_process?: number | null;
    /**
     * Memory
     *
     * Amount of memory to allocate in bytes
     */
    memory?: number | null;
    /**
     * Node Count
     *
     * Number of compute nodes to allocate
     */
    node_count?: number | null;
    /**
     * Process Count
     *
     * Total number of processes to launch
     */
    process_count?: number | null;
    /**
     * Processes Per Node
     *
     * Number of processes to launch per node
     */
    processes_per_node?: number | null;
};

/**
 * SimplonBinarySerializerParameters
 *
 * Configuration parameters for the Simplon binary serializer
 *
 * This serializer encodes event data into the Simplon 1.8 binary message
 * format as specified by Dectris
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"SimplonBinarySerializer"``
 *
 * data_source_to_serialize: Name of the data source whose array will be
 * compressed and embedded in each Simplon image message
 *
 * polarization_fraction: Fraction of linear polarization of the X-ray
 * beam (between 0 and 1)
 *
 * polarization_axis: Three-element list representing the polarization
 * axis direction vector
 *
 * data_collection_rate: Human-readable string describing the nominal
 * data collection rate (e.g. ``"120 Hz"``)
 *
 * detector_name: Human-readable name of the detector
 *
 * detector_type: Model or type string identifying the detector hardware
 */
export type SimplonBinarySerializerParameters = {
    /**
     * Data Collection Rate
     */
    data_collection_rate: string;
    /**
     * Data Source To Serialize
     */
    data_source_to_serialize: string;
    /**
     * Detector Name
     */
    detector_name: string;
    /**
     * Detector Type
     */
    detector_type: string;
    /**
     * Polarization Axis
     */
    polarization_axis: Array<number>;
    /**
     * Polarization Fraction
     */
    polarization_fraction: number;
    /**
     * Type
     */
    type: 'SimplonBinarySerializer';
};

/**
 * SourceIdentifierParameters
 *
 * Parameters for source identifier data source interface
 */
export type SourceIdentifierParameters = {
    /**
     * Type
     */
    type: 'SourceIdentifier';
};

/**
 * TransferCreate
 */
export type TransferCreate = {
    cache_mode?: CacheMode;
    job_spec_override?: JobSpec | null;
    parameters: Parameters;
};

/**
 * TransferDetail
 */
export type TransferDetail = {
    cache_mode: CacheMode;
    connection_info?: ConsumerConnectionInfo | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Experiment
     */
    experiment: string;
    /**
     * Id
     */
    id: string;
    /**
     * Requested By
     */
    requested_by: string;
    /**
     * Run
     */
    run: string;
    state: TransferState;
    /**
     * Transitions
     */
    transitions?: Array<TransitionPublic>;
};

/**
 * TransferLogIndex
 */
export type TransferLogIndex = {
    /**
     * Streams
     */
    streams: Array<TransferLogStreamInfo>;
    /**
     * Transfer Id
     */
    transfer_id: string;
};

/**
 * TransferLogStreamInfo
 *
 * One log stream's resolved location and (best-effort) availability.
 */
export type TransferLogStreamInfo = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Modified At
     */
    modified_at?: string | null;
    /**
     * Path
     */
    path: string;
    /**
     * Size
     */
    size?: number | null;
    stream: LogStream;
};

/**
 * TransferPublic
 */
export type TransferPublic = {
    cache_mode: CacheMode;
    connection_info?: ConsumerConnectionInfo | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Experiment
     */
    experiment: string;
    /**
     * Id
     */
    id: string;
    /**
     * Requested By
     */
    requested_by: string;
    /**
     * Run
     */
    run: string;
    state: TransferState;
};

/**
 * TransferState
 */
export type TransferState = 'provisioning' | 'ready' | 'canceling' | 'canceled' | 'completed' | 'failed';

/**
 * TransfersPublic
 */
export type TransfersPublic = {
    /**
     * Count
     */
    count: number;
    /**
     * Data
     */
    data: Array<TransferPublic>;
};

/**
 * TransitionPublic
 */
export type TransitionPublic = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Info
     */
    info?: string | null;
    source?: TransitionSource | null;
    state: TransferState;
};

/**
 * TransitionSource
 */
export type TransitionSource = 'producer' | 'cache' | 'user' | 'orchestrator';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VolumeMount
 *
 * Represents a volume mount for a container.
 */
export type VolumeMount = {
    /**
     * Additional Properties
     */
    additional_properties?: {
        [key: string]: unknown;
    };
    /**
     * Read Only
     *
     * Whether the mount should be read-only
     */
    read_only?: boolean | null;
    /**
     * Source
     *
     * The source path on the host system to mount
     */
    source: string;
    /**
     * Target
     *
     * The target path inside the container where the volume will be mounted
     */
    target: string;
};

export type GetCachesCachesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Experiment
         */
        experiment: string;
    };
    url: '/caches/';
};

export type GetCachesCachesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCachesCachesGetError = GetCachesCachesGetErrors[keyof GetCachesCachesGetErrors];

export type GetCachesCachesGetResponses = {
    /**
     * Successful Response
     */
    200: CachesPublic;
};

export type GetCachesCachesGetResponse = GetCachesCachesGetResponses[keyof GetCachesCachesGetResponses];

export type ShutdownCacheCachesCacheIdDeleteData = {
    body?: never;
    path: {
        /**
         * Cache Id
         */
        cache_id: string;
    };
    query?: never;
    url: '/caches/{cache_id}';
};

export type ShutdownCacheCachesCacheIdDeleteErrors = {
    /**
     * Conflict
     */
    409: CacheShutdownConflict;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ShutdownCacheCachesCacheIdDeleteError = ShutdownCacheCachesCacheIdDeleteErrors[keyof ShutdownCacheCachesCacheIdDeleteErrors];

export type ShutdownCacheCachesCacheIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ShutdownCacheCachesCacheIdDeleteResponse = ShutdownCacheCachesCacheIdDeleteResponses[keyof ShutdownCacheCachesCacheIdDeleteResponses];

export type GetTransfersTransfersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * State
         */
        state?: TransferState | null;
    };
    url: '/transfers/';
};

export type GetTransfersTransfersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransfersTransfersGetError = GetTransfersTransfersGetErrors[keyof GetTransfersTransfersGetErrors];

export type GetTransfersTransfersGetResponses = {
    /**
     * Successful Response
     */
    200: TransfersPublic;
};

export type GetTransfersTransfersGetResponse = GetTransfersTransfersGetResponses[keyof GetTransfersTransfersGetResponses];

export type NewTransferTransfersPostData = {
    body: TransferCreate;
    path?: never;
    query?: never;
    url: '/transfers/';
};

export type NewTransferTransfersPostErrors = {
    /**
     * Unprocessable Content
     */
    422: InsufficientTokenLifetimeError;
};

export type NewTransferTransfersPostError = NewTransferTransfersPostErrors[keyof NewTransferTransfersPostErrors];

export type NewTransferTransfersPostResponses = {
    /**
     * Successful Response
     */
    201: TransferPublic;
};

export type NewTransferTransfersPostResponse = NewTransferTransfersPostResponses[keyof NewTransferTransfersPostResponses];

export type CancelTransferTransfersTransferIdDeleteData = {
    body?: never;
    path: {
        /**
         * Transfer Id
         */
        transfer_id: string;
    };
    query?: never;
    url: '/transfers/{transfer_id}';
};

export type CancelTransferTransfersTransferIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelTransferTransfersTransferIdDeleteError = CancelTransferTransfersTransferIdDeleteErrors[keyof CancelTransferTransfersTransferIdDeleteErrors];

export type CancelTransferTransfersTransferIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type CancelTransferTransfersTransferIdDeleteResponse = CancelTransferTransfersTransferIdDeleteResponses[keyof CancelTransferTransfersTransferIdDeleteResponses];

export type GetTransferTransfersTransferIdGetData = {
    body?: never;
    path: {
        /**
         * Transfer Id
         */
        transfer_id: string;
    };
    query?: never;
    url: '/transfers/{transfer_id}';
};

export type GetTransferTransfersTransferIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransferTransfersTransferIdGetError = GetTransferTransfersTransferIdGetErrors[keyof GetTransferTransfersTransferIdGetErrors];

export type GetTransferTransfersTransferIdGetResponses = {
    /**
     * Successful Response
     */
    200: TransferDetail;
};

export type GetTransferTransfersTransferIdGetResponse = GetTransferTransfersTransferIdGetResponses[keyof GetTransferTransfersTransferIdGetResponses];

export type GetTransferLogsTransfersTransferIdLogsGetData = {
    body?: never;
    path: {
        /**
         * Transfer Id
         */
        transfer_id: string;
    };
    query?: never;
    url: '/transfers/{transfer_id}/logs';
};

export type GetTransferLogsTransfersTransferIdLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransferLogsTransfersTransferIdLogsGetError = GetTransferLogsTransfersTransferIdLogsGetErrors[keyof GetTransferLogsTransfersTransferIdLogsGetErrors];

export type GetTransferLogsTransfersTransferIdLogsGetResponses = {
    /**
     * Successful Response
     */
    200: TransferLogIndex;
};

export type GetTransferLogsTransfersTransferIdLogsGetResponse = GetTransferLogsTransfersTransferIdLogsGetResponses[keyof GetTransferLogsTransfersTransferIdLogsGetResponses];

export type GetTransferLogTransfersTransferIdLogsStreamGetData = {
    body?: never;
    path: {
        /**
         * Transfer Id
         */
        transfer_id: string;
        stream: LogStream;
    };
    query?: {
        mode?: LogReadMode;
        /**
         * Lines
         */
        lines?: number;
        /**
         * Bytes
         */
        bytes?: number | null;
    };
    url: '/transfers/{transfer_id}/logs/{stream}';
};

export type GetTransferLogTransfersTransferIdLogsStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransferLogTransfersTransferIdLogsStreamGetError = GetTransferLogTransfersTransferIdLogsStreamGetErrors[keyof GetTransferLogTransfersTransferIdLogsStreamGetErrors];

export type GetTransferLogTransfersTransferIdLogsStreamGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GetTransferLogTransfersTransferIdLogsStreamGetResponse = GetTransferLogTransfersTransferIdLogsStreamGetResponses[keyof GetTransferLogTransfersTransferIdLogsStreamGetResponses];
