// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * BatchProcessingPipelineParameters
 *
 * Configuration parameters for the Batch Processing Pipeline
 *
 * This pipeline accumulates individual events into fixed-size batches before
 * passing them downstream
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BatchProcessingPipeline"``
 *
 * batch_size: Number of events to accumulate per batch
 */
export const zBatchProcessingPipelineParameters = z.object({
    batch_size: z.int(),
    type: z.literal('BatchProcessingPipeline')
});

/**
 * BinaryDataStreamingDataHandlerParameters
 *
 * Configuration parameters for the Binary Data Streaming Data Handler
 *
 * This data handler forwards serialized byte objects to one or more remote
 * endpoints over a ZMQ PUSH socket
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BinaryDataStreamingDataHandler"``
 *
 * urls: List of endpoint URLs to bind to (server mode) or connect to
 * (client mode)
 *
 * distribute: Boolean, if True: round robin connect the ranks, False: all ranks connect to all urls and send the same data
 *
 * buffer: buffer size, if set to 0 the OS default is used
 *
 * role: Whether this node acts as the ZMQ ``"server"`` (binds) or
 * ``"client"`` (connects). Defaults to ``"server"``
 *
 * library: Underlying transport library to use. Currently only ``"zmq"``
 * is supported. Defaults to ``"zmq"``
 *
 * socket_type: Socket pattern to use. Currently only ``"push"`` is
 * supported. Defaults to ``"push"``
 */
export const zBinaryDataStreamingDataHandlerParameters = z.object({
    buffer: z.int().optional().default(0),
    distribute: z.boolean().optional().default(true),
    library: z.literal('zmq').optional().default('zmq'),
    role: z.enum(['server', 'client']).optional(),
    socket_type: z.literal('push').optional().default('push'),
    type: z.literal('BinaryDataStreamingDataHandler'),
    urls: z.array(z.string())
});

/**
 * BinaryFileWritingDataHandlerParameters
 *
 * Configuration parameters for the Binary File Writing Data Handler
 *
 * This data handler writes each serialized byte object to a separate file on
 * the filesystem
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"BinaryFileWritingDataHandler"``
 *
 * file_prefix: Optional string prepended to every output filename,
 * separated from the rest of the name by an underscore. Defaults to
 * ``""`` (no prefix)
 *
 * file_suffix: File extension used for output files, without the leading
 * dot. Defaults to ``"h5"``
 *
 * write_directory: Directory in which output files are created. The
 * directory is created (including parents) if it does not already
 * exist. Defaults to the current working directory
 */
export const zBinaryFileWritingDataHandlerParameters = z.object({
    file_prefix: z.string().optional().default(''),
    file_suffix: z.string().optional().default('h5'),
    type: z.literal('BinaryFileWritingDataHandler'),
    write_directory: z.string().optional()
});

/**
 * CacheMode
 */
export const zCacheMode = z.enum(['per_transfer', 'shared']);

/**
 * CacheShutdownConflict
 */
export const zCacheShutdownConflict = z.object({
    active_transfer_count: z.int(),
    message: z.string()
});

/**
 * CacheState
 *
 * Observed fastcache cache lifecycle.
 */
export const zCacheState = z.enum([
    'new',
    'queued',
    'active',
    'completed',
    'failed',
    'canceled'
]);

/**
 * CacheStatusPublic
 */
export const zCacheStatusPublic = z.object({
    id: z.uuid(),
    state: zCacheState
});

/**
 * CachesPublic
 */
export const zCachesPublic = z.object({
    data: z.array(zCacheStatusPublic)
});

/**
 * ConstValueParameters
 *
 * Parameters for ConstValue class
 */
export const zConstValueParameters = z.object({
    dtype: z.string(),
    type: z.literal('ConstValue'),
    value: z.union([
        z.int(),
        z.number(),
        z.array(z.union([z.int(), z.number()]))
    ])
});

/**
 * ConsumerSocket
 *
 * ZMQ socket the consumer connects with.
 *
 * ``dealer`` and ``req`` are request-driven: the consumer asks for each
 * message. fastcache only reports metrics under ``pull``.
 */
export const zConsumerSocket = z.enum([
    'pull',
    'dealer',
    'req'
]);

/**
 * ConsumerConnectionInfo
 *
 * The cache socket the consumer connects to, and how to dial it.
 */
export const zConsumerConnectionInfo = z.object({
    host: z.string(),
    port: z.int(),
    socket: zConsumerSocket,
    uri: z.string()
});

/**
 * CrystfelPreprocessingPipelineParameters
 *
 * Configuration parameters for the CrystFEL Preprocessing Pipeline
 *
 * This pipeline lays out the data in a format that is understood by the
 * CrystFEL Serial Crystalography Processing software.
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"CrystfelPreprocessingPipeline"``
 */
export const zCrystfelPreprocessingPipelineParameters = z.object({
    type: z.literal('CrystfelPreprocessingPipeline')
});

/**
 * GenericRandomNumpyArrayParameters
 *
 * Parameters for the GenericRandomNumpyArray class
 */
export const zGenericRandomNumpyArrayParameters = z.object({
    always_random: z.boolean().optional().default(true),
    array_dtype: z.string(),
    array_shape: z.union([
        z.int(),
        z.array(z.int())
    ]),
    type: z.literal('GenericRandomNumpyArray')
});

/**
 * HDF5BinarySerializerParameters
 *
 * Configuration parameters for the HDF5 binary serializer
 *
 * This serializer encodes a batch of event data arrays into an in-memory
 * HDF5 file. Optional compression can be applied to each dataset
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"HDF5BinarySerializer"``
 *
 * compression_level: Compression level passed to the chosen algorithm.
 * Interpretation depends on the algorithm. Defaults to ``3``
 *
 * compression: Compression algorithm to use. Supported values are
 * ``"gzip"``, ``"gzip_with_shuffle"``, ``"bitshuffle_with_lz4"``,
 * ``"bitshuffle_with_zstd"``, and ``"zfp"``. Set to ``None`` to
 * disable compression. Defaults to ``None``
 *
 * fields: Dictionary storing the mapping from data source name to the
 * HDF5 dataset path under which that source's data will be stored
 */
export const zHdf5BinarySerializerParameters = z.object({
    compression: z.enum([
        'gzip',
        'gzip_with_shuffle',
        'bitshuffle_with_lz4',
        'bitshuffle_with_zstd',
        'zfp'
    ]).nullish(),
    compression_level: z.int().optional().default(0),
    fields: z.record(z.string(), z.string()),
    type: z.literal('HDF5BinarySerializer')
});

/**
 * InsufficientTokenLifetimeError
 */
export const zInsufficientTokenLifetimeError = z.object({
    detail: z.string(),
    remaining_seconds: z.int(),
    required_seconds: z.int()
});

/**
 * InternalEventSourceParameters
 *
 * Configuration parameters for the Internal Event Source
 *
 * This event source generates synthetic events entirely in-process and does
 * not depend on any external data-acquisition framework. It is intended
 * mainly for testing and development
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"InternalEventSource"``
 *
 * number_of_events_to_generate: Total number of synthetic events to
 * produce before the source is exhausted
 */
export const zInternalEventSourceParameters = z.object({
    number_of_events_to_generate: z.int(),
    type: z.literal('InternalEventSource')
});

/**
 * JobAttributes
 *
 * Additional attributes and scheduling parameters for a job.
 */
export const zJobAttributes = z.object({
    account: z.string().min(1).nullish(),
    additional_properties: z.record(z.string(), z.unknown()).optional().default({}),
    custom_attributes: z.record(z.string(), z.string()).nullish(),
    duration: z.int().gte(1).nullish(),
    queue_name: z.string().min(1).nullish(),
    reservation_id: z.string().min(1).nullish()
});

/**
 * LogReadMode
 */
export const zLogReadMode = z.enum(['head', 'tail']);

/**
 * LogStream
 */
export const zLogStream = z.enum([
    'cache',
    'producer_stdout',
    'producer_stderr'
]);

/**
 * Message
 */
export const zMessage = z.object({
    message: z.string()
});

/**
 * MsgpackBinarySerializerParameters
 *
 * Configuration parameters for the MsgPack binary serializer
 *
 * This serializer encodes a batch of event data arrays into a MsgPack binary
 * object.
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"MsgpackBinarySerializer"``
 */
export const zMsgpackBinarySerializerParameters = z.object({
    type: z.literal('MsgpackBinarySerializer')
});

/**
 * PeaknetPreprocessingPipelineParameters
 *
 * Configuration parameters for the PeakNet Preprocessing Pipeline
 *
 * This pipeline pads detector images to a uniform size, accumulates them
 * into batches, and optionally adds a channel dimension, preparing the data
 * for inference with the PeakNet model
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"PeaknetPreprocessingPipeline"``
 *
 * batch_size: Number of events to accumulate per batch
 *
 * target_height: Target image height (in pixels) after padding
 *
 * target_width: Target image width (in pixels) after padding
 *
 * pad_style: How to distribute padding around the image; either
 * ``"center"`` (equal padding on both sides) or ``"bottom-right"``
 * (padding added only to the bottom and right edges)
 * Defaults to ``"center"``
 *
 * add_channel_dim: Whether to insert a channel dimension after batching,
 * converting (B, H, W) arrays to (B, C, H, W). Defaults to ``True``
 *
 * num_channels: Number of channels to produce when ``add_channel_dim``
 * is ``True``. Defaults to ``1``
 */
export const zPeaknetPreprocessingPipelineParameters = z.object({
    add_channel_dim: z.boolean().optional().default(true),
    batch_size: z.int(),
    num_channels: z.int().optional().default(1),
    pad_style: z.enum(['center', 'bottom-right']).optional(),
    target_height: z.int(),
    target_width: z.int(),
    type: z.literal('PeaknetPreprocessingPipeline')
});

/**
 * Psana1DetectorInterfaceParameters
 */
export const zPsana1DetectorInterfaceParameters = z.object({
    psana_fields: z.union([
        z.array(z.string()),
        z.string()
    ]).nullish(),
    psana_name: z.string(),
    type: z.literal('Psana1DetectorInterface')
});

/**
 * Psana1EventSourceParameters
 *
 * Configuration parameters for the Psana1 Event Source
 *
 * This event source reads events using the psana1 framework (LCLS-I)
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"Psana1EventSource"``
 */
export const zPsana1EventSourceParameters = z.object({
    type: z.literal('Psana1EventSource')
});

/**
 * Psana1TimestampParameters
 *
 * Parameters for psana1 timestamp interface
 */
export const zPsana1TimestampParameters = z.object({
    type: z.literal('Psana1Timestamp')
});

/**
 * Psana2DetectorInterfaceParameters
 */
export const zPsana2DetectorInterfaceParameters = z.object({
    dtype: z.string().nullish(),
    psana_fields: z.union([
        z.array(z.string()),
        z.string()
    ]).nullish(),
    psana_name: z.string(),
    type: z.literal('Psana2DetectorInterface')
});

/**
 * Psana2EventSourceParameters
 *
 * Configuration parameters for the Psana2 Event Source
 *
 * This event source reads events using the psana2 framework (LCLS-II)
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"Psana2EventSource"``
 */
export const zPsana2EventSourceParameters = z.object({
    type: z.literal('Psana2EventSource')
});

/**
 * Psana2RunInfoParameters
 *
 * Parameters for run info data source interface
 */
export const zPsana2RunInfoParameters = z.object({
    type: z.literal('Psana2RunInfo')
});

/**
 * Psana2TimestampParameters
 *
 * Parameters for psana2 timestamp interface
 */
export const zPsana2TimestampParameters = z.object({
    type: z.literal('Psana2Timestamp')
});

/**
 * ResourceSpec
 *
 * Specification of computational resources required for a job.
 */
export const zResourceSpec = z.object({
    additional_properties: z.record(z.string(), z.unknown()).optional().default({}),
    cpu_cores_per_process: z.int().gte(1).nullish(),
    exclusive_node_use: z.boolean().nullish().default(true),
    gpu_cores_per_process: z.int().gte(1).nullish(),
    memory: z.int().gte(1).nullish(),
    node_count: z.int().gte(1).nullish(),
    process_count: z.int().gte(1).nullish(),
    processes_per_node: z.int().gte(1).nullish()
});

/**
 * SimplonBinarySerializerParameters
 *
 * Configuration parameters for the Simplon binary serializer
 *
 * This serializer encodes event data into the Simplon 1.8 binary message
 * format as specified by Dectris
 *
 * Attributes:
 *
 * type: Discriminator field, must be ``"SimplonBinarySerializer"``
 *
 * data_source_to_serialize: Name of the data source whose array will be
 * compressed and embedded in each Simplon image message
 *
 * polarization_fraction: Fraction of linear polarization of the X-ray
 * beam (between 0 and 1)
 *
 * polarization_axis: Three-element list representing the polarization
 * axis direction vector
 *
 * data_collection_rate: Human-readable string describing the nominal
 * data collection rate (e.g. ``"120 Hz"``)
 *
 * detector_name: Human-readable name of the detector
 *
 * detector_type: Model or type string identifying the detector hardware
 */
export const zSimplonBinarySerializerParameters = z.object({
    data_collection_rate: z.string(),
    data_source_to_serialize: z.string(),
    detector_name: z.string(),
    detector_type: z.string(),
    polarization_axis: z.array(z.number()),
    polarization_fraction: z.number(),
    type: z.literal('SimplonBinarySerializer')
});

/**
 * SourceIdentifierParameters
 *
 * Parameters for source identifier data source interface
 */
export const zSourceIdentifierParameters = z.object({
    type: z.literal('SourceIdentifier')
});

/**
 * Parameters
 *
 * Top-level configuration parameters for an lclstreamer run
 *
 * This model aggregates all sub-component configuration into a single object
 *
 * Attributes:
 *
 * source_identifier: A string that uniquely identifies the data source
 * (e.g. a psana data source string)
 *
 * skip_incomplete_events: When ``True``, events for which one or more
 * data sources returned no data are silently dropped from the stream
 *
 * event_source: Configuration for the event source
 *
 * data_sources: Mapping from arbitrary data source names to the
 * configuration parameters of each data source
 *
 * processing_pipeline: Configuration for the Processing Pipeline applied
 * to the event stream
 *
 * data_serializer: Configuration for the serializer that converts
 * processed events into byte objects
 *
 * data_handlers: Ordered list of data handler configurations; each
 * handler receives the serialized byte object in turn
 */
export const zParameters = z.object({
    data_handlers: z.array(z.union([z.object({
            type: z.literal('BinaryDataStreamingDataHandler')
        }).and(zBinaryDataStreamingDataHandlerParameters), z.object({
            type: z.literal('BinaryFileWritingDataHandler')
        }).and(zBinaryFileWritingDataHandlerParameters)])),
    data_serializer: z.union([
        z.object({
            type: z.literal('HDF5BinarySerializer')
        }).and(zHdf5BinarySerializerParameters),
        z.object({
            type: z.literal('SimplonBinarySerializer')
        }).and(zSimplonBinarySerializerParameters),
        z.object({
            type: z.literal('MsgpackBinarySerializer')
        }).and(zMsgpackBinarySerializerParameters)
    ]),
    data_sources: z.record(z.string(), z.union([
        z.object({
            type: z.literal('GenericRandomNumpyArray')
        }).and(zGenericRandomNumpyArrayParameters),
        z.object({
            type: z.literal('ConstValue')
        }).and(zConstValueParameters),
        z.object({
            type: z.literal('Psana1DetectorInterface')
        }).and(zPsana1DetectorInterfaceParameters),
        z.object({
            type: z.literal('Psana2DetectorInterface')
        }).and(zPsana2DetectorInterfaceParameters),
        z.object({
            type: z.literal('Psana1Timestamp')
        }).and(zPsana1TimestampParameters),
        z.object({
            type: z.literal('Psana2Timestamp')
        }).and(zPsana2TimestampParameters),
        z.object({
            type: z.literal('SourceIdentifier')
        }).and(zSourceIdentifierParameters),
        z.object({
            type: z.literal('Psana2RunInfo')
        }).and(zPsana2RunInfoParameters)
    ])),
    event_source: z.union([
        z.object({
            type: z.literal('InternalEventSource')
        }).and(zInternalEventSourceParameters),
        z.object({
            type: z.literal('Psana1EventSource')
        }).and(zPsana1EventSourceParameters),
        z.object({
            type: z.literal('Psana2EventSource')
        }).and(zPsana2EventSourceParameters)
    ]),
    processing_pipeline: z.union([
        z.object({
            type: z.literal('BatchProcessingPipeline')
        }).and(zBatchProcessingPipelineParameters),
        z.object({
            type: z.literal('PeaknetPreprocessingPipeline')
        }).and(zPeaknetPreprocessingPipelineParameters),
        z.object({
            type: z.literal('CrystfelPreprocessingPipeline')
        }).and(zCrystfelPreprocessingPipelineParameters)
    ]),
    skip_incomplete_events: z.boolean(),
    source_identifier: z.string()
});

/**
 * TransferLogStreamInfo
 *
 * One log stream's resolved location and (best-effort) availability.
 */
export const zTransferLogStreamInfo = z.object({
    available: z.boolean(),
    modified_at: z.iso.datetime().nullish(),
    path: z.string(),
    size: z.int().nullish(),
    stream: zLogStream
});

/**
 * TransferLogIndex
 */
export const zTransferLogIndex = z.object({
    streams: z.array(zTransferLogStreamInfo),
    transfer_id: z.uuid()
});

/**
 * TransferState
 */
export const zTransferState = z.enum([
    'provisioning',
    'ready',
    'canceling',
    'canceled',
    'completed',
    'failed'
]);

/**
 * TransferPublic
 */
export const zTransferPublic = z.object({
    cache_mode: zCacheMode,
    connection_info: zConsumerConnectionInfo.nullish(),
    created_at: z.iso.datetime(),
    experiment: z.string(),
    id: z.uuid(),
    requested_by: z.string(),
    run: z.string(),
    state: zTransferState
});

/**
 * TransfersPublic
 */
export const zTransfersPublic = z.object({
    count: z.int(),
    data: z.array(zTransferPublic)
});

/**
 * TransitionSource
 */
export const zTransitionSource = z.enum([
    'producer',
    'cache',
    'user',
    'orchestrator'
]);

/**
 * TransitionPublic
 */
export const zTransitionPublic = z.object({
    created_at: z.iso.datetime(),
    info: z.string().nullish(),
    source: zTransitionSource.nullish(),
    state: zTransferState
});

/**
 * TransferDetail
 */
export const zTransferDetail = z.object({
    cache_mode: zCacheMode,
    connection_info: zConsumerConnectionInfo.nullish(),
    created_at: z.iso.datetime(),
    experiment: z.string(),
    id: z.uuid(),
    requested_by: z.string(),
    run: z.string(),
    state: zTransferState,
    transitions: z.array(zTransitionPublic).optional().default([])
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    ctx: z.record(z.string(), z.unknown()).optional(),
    input: z.unknown().optional(),
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * VolumeMount
 *
 * Represents a volume mount for a container.
 */
export const zVolumeMount = z.object({
    additional_properties: z.record(z.string(), z.unknown()).optional().default({}),
    read_only: z.boolean().nullish().default(true),
    source: z.string().min(1),
    target: z.string().min(1)
});

/**
 * Container
 *
 * Represents a container specification for job execution.  Implementation notes: The value of gpu_cores_per_process in ResourceSpec should be used to determine if the container should be run with GPU support. Likewise, the value of launcher in JobSpec should be used to determine if the container should be run with MPI support. The container should by default. be run with host networking.
 */
export const zContainer = z.object({
    additional_properties: z.record(z.string(), z.unknown()).optional().default({}),
    image: z.string().min(1),
    volume_mounts: z.array(zVolumeMount).nullish()
});

/**
 * JobSpec
 *
 * Specification for a job.
 */
export const zJobSpec = z.object({
    arguments: z.array(z.string()).nullish(),
    attributes: zJobAttributes.nullish(),
    container: zContainer.nullish(),
    directory: z.string().min(1).nullish(),
    environment: z.record(z.string(), z.string()).nullish(),
    executable: z.string().min(1).nullish(),
    inherit_environment: z.boolean().nullish().default(true),
    launcher: z.string().min(1).nullish(),
    name: z.string().min(1).nullish(),
    post_launch: z.string().min(1).nullish(),
    pre_launch: z.string().min(1).nullish(),
    resources: zResourceSpec.nullish(),
    stderr_path: z.string().min(1).nullish(),
    stdin_path: z.string().min(1).nullish(),
    stdout_path: z.string().min(1).nullish()
});

/**
 * TransferCreate
 */
export const zTransferCreate = z.object({
    cache_mode: zCacheMode.optional().default('per_transfer'),
    consumer_socket: zConsumerSocket.optional().default('pull'),
    job_spec_override: zJobSpec.nullish(),
    parameters: zParameters
});

export const zGetCachesCachesGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        experiment: z.string()
    })
});

/**
 * Successful Response
 */
export const zGetCachesCachesGetResponse = zCachesPublic;

export const zShutdownCacheCachesCacheIdDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        cache_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zShutdownCacheCachesCacheIdDeleteResponse = zMessage;

export const zGetTransfersTransfersGetData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        skip: z.int().optional().default(0),
        limit: z.int().optional().default(100),
        state: zTransferState.nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetTransfersTransfersGetResponse = zTransfersPublic;

export const zNewTransferTransfersPostData = z.object({
    body: zTransferCreate,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zNewTransferTransfersPostResponse = zTransferPublic;

export const zCancelTransferTransfersTransferIdDeleteData = z.object({
    body: z.never().optional(),
    path: z.object({
        transfer_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zCancelTransferTransfersTransferIdDeleteResponse = zMessage;

export const zGetTransferTransfersTransferIdGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        transfer_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGetTransferTransfersTransferIdGetResponse = zTransferDetail;

export const zGetTransferLogsTransfersTransferIdLogsGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        transfer_id: z.uuid()
    }),
    query: z.never().optional()
});

/**
 * Successful Response
 */
export const zGetTransferLogsTransfersTransferIdLogsGetResponse = zTransferLogIndex;

export const zGetTransferLogTransfersTransferIdLogsStreamGetData = z.object({
    body: z.never().optional(),
    path: z.object({
        transfer_id: z.uuid(),
        stream: zLogStream
    }),
    query: z.object({
        mode: zLogReadMode.optional().default('tail'),
        lines: z.int().gt(0).lte(10000).optional().default(200),
        bytes: z.int().gt(0).lte(10000000).nullish()
    }).optional()
});

/**
 * Successful Response
 */
export const zGetTransferLogTransfersTransferIdLogsStreamGetResponse = z.string();
