# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BinaryDataStreamingDataHandlerParameters(BaseModel):
    """
    Configuration parameters for the Binary Data Streaming Data Handler  This data handler forwards serialized byte objects to one or more remote endpoints over a ZMQ PUSH socket  Attributes:      type: Discriminator field, must be ``\"BinaryDataStreamingDataHandler\"``      urls: List of endpoint URLs to bind to (server mode) or connect to         (client mode)      distribute: Boolean, if True: round robin connect the ranks, False: all ranks connect to all urls and send the same data      buffer: buffer size, if set to 0 the OS default is used      role: Whether this node acts as the ZMQ ``\"server\"`` (binds) or         ``\"client\"`` (connects). Defaults to ``\"server\"``      library: Underlying transport library to use. Currently only ``\"zmq\"``         is supported. Defaults to ``\"zmq\"``      socket_type: Socket pattern to use. Currently only ``\"push\"`` is         supported. Defaults to ``\"push\"``
    """ # noqa: E501
    buffer: Optional[StrictInt] = 0
    distribute: Optional[StrictBool] = True
    library: Optional[StrictStr] = 'zmq'
    role: Optional[StrictStr] = 'client'
    socket_type: Optional[StrictStr] = 'push'
    type: StrictStr
    urls: List[StrictStr]
    __properties: ClassVar[List[str]] = ["buffer", "distribute", "library", "role", "socket_type", "type", "urls"]

    @field_validator('library')
    def library_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['zmq']):
            raise ValueError("must be one of enum values ('zmq')")
        return value

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['server', 'client']):
            raise ValueError("must be one of enum values ('server', 'client')")
        return value

    @field_validator('socket_type')
    def socket_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['push']):
            raise ValueError("must be one of enum values ('push')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BinaryDataStreamingDataHandler']):
            raise ValueError("must be one of enum values ('BinaryDataStreamingDataHandler')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BinaryDataStreamingDataHandlerParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BinaryDataStreamingDataHandlerParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "buffer": obj.get("buffer") if obj.get("buffer") is not None else 0,
            "distribute": obj.get("distribute") if obj.get("distribute") is not None else True,
            "library": obj.get("library") if obj.get("library") is not None else 'zmq',
            "role": obj.get("role") if obj.get("role") is not None else 'client',
            "socket_type": obj.get("socket_type") if obj.get("socket_type") is not None else 'push',
            "type": obj.get("type"),
            "urls": obj.get("urls")
        })
        return _obj


