# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BinaryFileWritingDataHandlerParameters(BaseModel):
    """
    Configuration parameters for the Binary File Writing Data Handler  This data handler writes each serialized byte object to a separate file on the filesystem  Attributes:      type: Discriminator field, must be ``\"BinaryFileWritingDataHandler\"``      file_prefix: Optional string prepended to every output filename,         separated from the rest of the name by an underscore. Defaults to         ``\"\"`` (no prefix)      file_suffix: File extension used for output files, without the leading         dot. Defaults to ``\"h5\"``      write_directory: Directory in which output files are created. The         directory is created (including parents) if it does not already         exist. Defaults to the current working directory
    """ # noqa: E501
    file_prefix: Optional[StrictStr] = ''
    file_suffix: Optional[StrictStr] = 'h5'
    type: StrictStr
    write_directory: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["file_prefix", "file_suffix", "type", "write_directory"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['BinaryFileWritingDataHandler']):
            raise ValueError("must be one of enum values ('BinaryFileWritingDataHandler')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BinaryFileWritingDataHandlerParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BinaryFileWritingDataHandlerParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file_prefix": obj.get("file_prefix") if obj.get("file_prefix") is not None else '',
            "file_suffix": obj.get("file_suffix") if obj.get("file_suffix") is not None else 'h5',
            "type": obj.get("type"),
            "write_directory": obj.get("write_directory")
        })
        return _obj


