# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lclstream_api_client._generated.models.const_value_parameters import ConstValueParameters
from lclstream_api_client._generated.models.generic_random_numpy_array_parameters import GenericRandomNumpyArrayParameters
from lclstream_api_client._generated.models.psana1_detector_interface_parameters import Psana1DetectorInterfaceParameters
from lclstream_api_client._generated.models.psana1_timestamp_parameters import Psana1TimestampParameters
from lclstream_api_client._generated.models.psana2_detector_interface_parameters import Psana2DetectorInterfaceParameters
from lclstream_api_client._generated.models.psana2_run_info_parameters import Psana2RunInfoParameters
from lclstream_api_client._generated.models.psana2_timestamp_parameters import Psana2TimestampParameters
from lclstream_api_client._generated.models.source_identifier_parameters import SourceIdentifierParameters
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DATASOURCESVALUE_ONE_OF_SCHEMAS = ["ConstValueParameters", "GenericRandomNumpyArrayParameters", "Psana1DetectorInterfaceParameters", "Psana1TimestampParameters", "Psana2DetectorInterfaceParameters", "Psana2RunInfoParameters", "Psana2TimestampParameters", "SourceIdentifierParameters"]

class DataSourcesValue(BaseModel):
    """
    DataSourcesValue
    """
    # data type: GenericRandomNumpyArrayParameters
    oneof_schema_1_validator: Optional[GenericRandomNumpyArrayParameters] = None
    # data type: ConstValueParameters
    oneof_schema_2_validator: Optional[ConstValueParameters] = None
    # data type: Psana1DetectorInterfaceParameters
    oneof_schema_3_validator: Optional[Psana1DetectorInterfaceParameters] = None
    # data type: Psana2DetectorInterfaceParameters
    oneof_schema_4_validator: Optional[Psana2DetectorInterfaceParameters] = None
    # data type: Psana1TimestampParameters
    oneof_schema_5_validator: Optional[Psana1TimestampParameters] = None
    # data type: Psana2TimestampParameters
    oneof_schema_6_validator: Optional[Psana2TimestampParameters] = None
    # data type: SourceIdentifierParameters
    oneof_schema_7_validator: Optional[SourceIdentifierParameters] = None
    # data type: Psana2RunInfoParameters
    oneof_schema_8_validator: Optional[Psana2RunInfoParameters] = None
    actual_instance: Optional[Union[ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters]] = None
    one_of_schemas: Set[str] = { "ConstValueParameters", "GenericRandomNumpyArrayParameters", "Psana1DetectorInterfaceParameters", "Psana1TimestampParameters", "Psana2DetectorInterfaceParameters", "Psana2RunInfoParameters", "Psana2TimestampParameters", "SourceIdentifierParameters" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DataSourcesValue.model_construct()
        error_messages = []
        match = 0
        # validate data type: GenericRandomNumpyArrayParameters
        if not isinstance(v, GenericRandomNumpyArrayParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GenericRandomNumpyArrayParameters`")
        else:
            match += 1
        # validate data type: ConstValueParameters
        if not isinstance(v, ConstValueParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ConstValueParameters`")
        else:
            match += 1
        # validate data type: Psana1DetectorInterfaceParameters
        if not isinstance(v, Psana1DetectorInterfaceParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Psana1DetectorInterfaceParameters`")
        else:
            match += 1
        # validate data type: Psana2DetectorInterfaceParameters
        if not isinstance(v, Psana2DetectorInterfaceParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Psana2DetectorInterfaceParameters`")
        else:
            match += 1
        # validate data type: Psana1TimestampParameters
        if not isinstance(v, Psana1TimestampParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Psana1TimestampParameters`")
        else:
            match += 1
        # validate data type: Psana2TimestampParameters
        if not isinstance(v, Psana2TimestampParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Psana2TimestampParameters`")
        else:
            match += 1
        # validate data type: SourceIdentifierParameters
        if not isinstance(v, SourceIdentifierParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SourceIdentifierParameters`")
        else:
            match += 1
        # validate data type: Psana2RunInfoParameters
        if not isinstance(v, Psana2RunInfoParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `Psana2RunInfoParameters`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DataSourcesValue with oneOf schemas: ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DataSourcesValue with oneOf schemas: ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GenericRandomNumpyArrayParameters
        try:
            instance.actual_instance = GenericRandomNumpyArrayParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ConstValueParameters
        try:
            instance.actual_instance = ConstValueParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Psana1DetectorInterfaceParameters
        try:
            instance.actual_instance = Psana1DetectorInterfaceParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Psana2DetectorInterfaceParameters
        try:
            instance.actual_instance = Psana2DetectorInterfaceParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Psana1TimestampParameters
        try:
            instance.actual_instance = Psana1TimestampParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Psana2TimestampParameters
        try:
            instance.actual_instance = Psana2TimestampParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SourceIdentifierParameters
        try:
            instance.actual_instance = SourceIdentifierParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into Psana2RunInfoParameters
        try:
            instance.actual_instance = Psana2RunInfoParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DataSourcesValue with oneOf schemas: ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DataSourcesValue with oneOf schemas: ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ConstValueParameters, GenericRandomNumpyArrayParameters, Psana1DetectorInterfaceParameters, Psana1TimestampParameters, Psana2DetectorInterfaceParameters, Psana2RunInfoParameters, Psana2TimestampParameters, SourceIdentifierParameters]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


