# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lclstream_api_client._generated.models.hdf5_binary_serializer_parameters import HDF5BinarySerializerParameters
from lclstream_api_client._generated.models.simplon_binary_serializer_parameters import SimplonBinarySerializerParameters
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

DATASERIALIZER_ONE_OF_SCHEMAS = ["HDF5BinarySerializerParameters", "SimplonBinarySerializerParameters"]

class DataSerializer(BaseModel):
    """
    DataSerializer
    """
    # data type: HDF5BinarySerializerParameters
    oneof_schema_1_validator: Optional[HDF5BinarySerializerParameters] = None
    # data type: SimplonBinarySerializerParameters
    oneof_schema_2_validator: Optional[SimplonBinarySerializerParameters] = None
    actual_instance: Optional[Union[HDF5BinarySerializerParameters, SimplonBinarySerializerParameters]] = None
    one_of_schemas: Set[str] = { "HDF5BinarySerializerParameters", "SimplonBinarySerializerParameters" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = DataSerializer.model_construct()
        error_messages = []
        match = 0
        # validate data type: HDF5BinarySerializerParameters
        if not isinstance(v, HDF5BinarySerializerParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HDF5BinarySerializerParameters`")
        else:
            match += 1
        # validate data type: SimplonBinarySerializerParameters
        if not isinstance(v, SimplonBinarySerializerParameters):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SimplonBinarySerializerParameters`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in DataSerializer with oneOf schemas: HDF5BinarySerializerParameters, SimplonBinarySerializerParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in DataSerializer with oneOf schemas: HDF5BinarySerializerParameters, SimplonBinarySerializerParameters. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into HDF5BinarySerializerParameters
        try:
            instance.actual_instance = HDF5BinarySerializerParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SimplonBinarySerializerParameters
        try:
            instance.actual_instance = SimplonBinarySerializerParameters.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into DataSerializer with oneOf schemas: HDF5BinarySerializerParameters, SimplonBinarySerializerParameters. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into DataSerializer with oneOf schemas: HDF5BinarySerializerParameters, SimplonBinarySerializerParameters. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], HDF5BinarySerializerParameters, SimplonBinarySerializerParameters]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


