# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class HDF5BinarySerializerParameters(BaseModel):
    """
    Configuration parameters for the HDF5 binary serializer  This serializer encodes a batch of event data arrays into an in-memory HDF5 file. Optional compression can be applied to each dataset  Attributes:      type: Discriminator field, must be ``\"HDF5BinarySerializer\"``      compression_level: Compression level passed to the chosen algorithm.         Interpretation depends on the algorithm. Defaults to ``3``      compression: Compression algorithm to use. Supported values are         ``\"gzip\"``, ``\"gzip_with_shuffle\"``, ``\"bitshuffle_with_lz4\"``,         ``\"bitshuffle_with_zstd\"``, and ``\"zfp\"``. Set to ``None`` to         disable compression. Defaults to ``None``      fields: Dictionary storing the mapping from data source name to the         HDF5 dataset path under which that source's data will be stored
    """ # noqa: E501
    compression: Optional[StrictStr] = None
    compression_level: Optional[StrictInt] = 0
    fields: Dict[str, StrictStr]
    type: StrictStr
    __properties: ClassVar[List[str]] = ["compression", "compression_level", "fields", "type"]

    @field_validator('compression')
    def compression_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['gzip', 'gzip_with_shuffle', 'bitshuffle_with_lz4', 'bitshuffle_with_zstd', 'zfp']):
            raise ValueError("must be one of enum values ('gzip', 'gzip_with_shuffle', 'bitshuffle_with_lz4', 'bitshuffle_with_zstd', 'zfp')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['HDF5BinarySerializer']):
            raise ValueError("must be one of enum values ('HDF5BinarySerializer')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HDF5BinarySerializerParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if compression (nullable) is None
        # and model_fields_set contains the field
        if self.compression is None and "compression" in self.model_fields_set:
            _dict['compression'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HDF5BinarySerializerParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compression": obj.get("compression"),
            "compression_level": obj.get("compression_level") if obj.get("compression_level") is not None else 0,
            "fields": obj.get("fields"),
            "type": obj.get("type")
        })
        return _obj


