# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from lclstream_api_client._generated.models.container import Container
from lclstream_api_client._generated.models.job_attributes import JobAttributes
from lclstream_api_client._generated.models.resource_spec import ResourceSpec
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JobSpec(BaseModel):
    """
    Specification for a job.
    """ # noqa: E501
    arguments: Optional[List[StrictStr]] = Field(default=None, description="Command-line arguments to pass to the executable or container")
    attributes: Optional[JobAttributes] = Field(default=None, description="Additional job attributes such as duration, queue, and account")
    container: Optional[Container] = Field(default=None, description="Container specification for containerized execution")
    directory: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Working directory for the job")
    environment: Optional[Dict[str, StrictStr]] = Field(default=None, description="Environment variables to set for the job. If container is specified, these will be set inside the container.")
    executable: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Path to the executable to run. If container is specified, this will be used as the entrypoint to the container.")
    inherit_environment: Optional[StrictBool] = Field(default=None, description="Whether to inherit the environment variables from the submission environment")
    launcher: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Job launcher to use (e.g., 'mpirun', 'srun')")
    name: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Name of the job")
    post_launch: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Script or commands to run after the job completes")
    pre_launch: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Script or commands to run before launching the job")
    resources: Optional[ResourceSpec] = Field(default=None, description="Resource requirements for the job")
    stderr_path: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Path to file to write standard error")
    stdin_path: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Path to file to use as standard input")
    stdout_path: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Path to file to write standard output")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["arguments", "attributes", "container", "directory", "environment", "executable", "inherit_environment", "launcher", "name", "post_launch", "pre_launch", "resources", "stderr_path", "stdin_path", "stdout_path"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attributes
        if self.attributes:
            _dict['attributes'] = self.attributes.to_dict()
        # override the default output from pydantic by calling `to_dict()` of container
        if self.container:
            _dict['container'] = self.container.to_dict()
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if arguments (nullable) is None
        # and model_fields_set contains the field
        if self.arguments is None and "arguments" in self.model_fields_set:
            _dict['arguments'] = None

        # set to None if attributes (nullable) is None
        # and model_fields_set contains the field
        if self.attributes is None and "attributes" in self.model_fields_set:
            _dict['attributes'] = None

        # set to None if container (nullable) is None
        # and model_fields_set contains the field
        if self.container is None and "container" in self.model_fields_set:
            _dict['container'] = None

        # set to None if directory (nullable) is None
        # and model_fields_set contains the field
        if self.directory is None and "directory" in self.model_fields_set:
            _dict['directory'] = None

        # set to None if environment (nullable) is None
        # and model_fields_set contains the field
        if self.environment is None and "environment" in self.model_fields_set:
            _dict['environment'] = None

        # set to None if executable (nullable) is None
        # and model_fields_set contains the field
        if self.executable is None and "executable" in self.model_fields_set:
            _dict['executable'] = None

        # set to None if inherit_environment (nullable) is None
        # and model_fields_set contains the field
        if self.inherit_environment is None and "inherit_environment" in self.model_fields_set:
            _dict['inherit_environment'] = None

        # set to None if launcher (nullable) is None
        # and model_fields_set contains the field
        if self.launcher is None and "launcher" in self.model_fields_set:
            _dict['launcher'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if post_launch (nullable) is None
        # and model_fields_set contains the field
        if self.post_launch is None and "post_launch" in self.model_fields_set:
            _dict['post_launch'] = None

        # set to None if pre_launch (nullable) is None
        # and model_fields_set contains the field
        if self.pre_launch is None and "pre_launch" in self.model_fields_set:
            _dict['pre_launch'] = None

        # set to None if resources (nullable) is None
        # and model_fields_set contains the field
        if self.resources is None and "resources" in self.model_fields_set:
            _dict['resources'] = None

        # set to None if stderr_path (nullable) is None
        # and model_fields_set contains the field
        if self.stderr_path is None and "stderr_path" in self.model_fields_set:
            _dict['stderr_path'] = None

        # set to None if stdin_path (nullable) is None
        # and model_fields_set contains the field
        if self.stdin_path is None and "stdin_path" in self.model_fields_set:
            _dict['stdin_path'] = None

        # set to None if stdout_path (nullable) is None
        # and model_fields_set contains the field
        if self.stdout_path is None and "stdout_path" in self.model_fields_set:
            _dict['stdout_path'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arguments": obj.get("arguments"),
            "attributes": JobAttributes.from_dict(obj["attributes"]) if obj.get("attributes") is not None else None,
            "container": Container.from_dict(obj["container"]) if obj.get("container") is not None else None,
            "directory": obj.get("directory"),
            "environment": obj.get("environment"),
            "executable": obj.get("executable"),
            "inherit_environment": obj.get("inherit_environment"),
            "launcher": obj.get("launcher"),
            "name": obj.get("name"),
            "post_launch": obj.get("post_launch"),
            "pre_launch": obj.get("pre_launch"),
            "resources": ResourceSpec.from_dict(obj["resources"]) if obj.get("resources") is not None else None,
            "stderr_path": obj.get("stderr_path"),
            "stdin_path": obj.get("stdin_path"),
            "stdout_path": obj.get("stdout_path")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


