# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from lclstream_api_client._generated.models.data_handlers_inner import DataHandlersInner
from lclstream_api_client._generated.models.data_serializer import DataSerializer
from lclstream_api_client._generated.models.data_sources_value import DataSourcesValue
from lclstream_api_client._generated.models.event_source import EventSource
from lclstream_api_client._generated.models.processing_pipeline import ProcessingPipeline
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Parameters(BaseModel):
    """
    Top-level configuration parameters for an lclstreamer run  This model aggregates all sub-component configuration into a single object  Attributes:      source_identifier: A string that uniquely identifies the data source         (e.g. a psana data source string)      skip_incomplete_events: When ``True``, events for which one or more         data sources returned no data are silently dropped from the stream      event_source: Configuration for the event source      data_sources: Mapping from arbitrary data source names to the         configuration parameters of each data source      processing_pipeline: Configuration for the Processing Pipeline applied         to the event stream      data_serializer: Configuration for the serializer that converts         processed events into byte objects      data_handlers: Ordered list of data handler configurations; each         handler receives the serialized byte object in turn
    """ # noqa: E501
    data_handlers: List[DataHandlersInner]
    data_serializer: DataSerializer
    data_sources: Dict[str, DataSourcesValue]
    event_source: EventSource
    processing_pipeline: ProcessingPipeline
    skip_incomplete_events: StrictBool
    source_identifier: StrictStr
    __properties: ClassVar[List[str]] = ["data_handlers", "data_serializer", "data_sources", "event_source", "processing_pipeline", "skip_incomplete_events", "source_identifier"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Parameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_handlers (list)
        _items = []
        if self.data_handlers:
            for _item_data_handlers in self.data_handlers:
                if _item_data_handlers:
                    _items.append(_item_data_handlers.to_dict())
            _dict['data_handlers'] = _items
        # override the default output from pydantic by calling `to_dict()` of data_serializer
        if self.data_serializer:
            _dict['data_serializer'] = self.data_serializer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in data_sources (dict)
        _field_dict = {}
        if self.data_sources:
            for _key_data_sources in self.data_sources:
                if self.data_sources[_key_data_sources]:
                    _field_dict[_key_data_sources] = self.data_sources[_key_data_sources].to_dict()
            _dict['data_sources'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of event_source
        if self.event_source:
            _dict['event_source'] = self.event_source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of processing_pipeline
        if self.processing_pipeline:
            _dict['processing_pipeline'] = self.processing_pipeline.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Parameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_handlers": [DataHandlersInner.from_dict(_item) for _item in obj["data_handlers"]] if obj.get("data_handlers") is not None else None,
            "data_serializer": DataSerializer.from_dict(obj["data_serializer"]) if obj.get("data_serializer") is not None else None,
            "data_sources": dict(
                (_k, DataSourcesValue.from_dict(_v))
                for _k, _v in obj["data_sources"].items()
            )
            if obj.get("data_sources") is not None
            else None,
            "event_source": EventSource.from_dict(obj["event_source"]) if obj.get("event_source") is not None else None,
            "processing_pipeline": ProcessingPipeline.from_dict(obj["processing_pipeline"]) if obj.get("processing_pipeline") is not None else None,
            "skip_incomplete_events": obj.get("skip_incomplete_events"),
            "source_identifier": obj.get("source_identifier")
        })
        return _obj


