# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PeaknetPreprocessingPipelineParameters(BaseModel):
    """
    Configuration parameters for the PeakNet Preprocessing Pipeline  This pipeline pads detector images to a uniform size, accumulates them into batches, and optionally adds a channel dimension, preparing the data for inference with the PeakNet model  Attributes:      type: Discriminator field, must be ``\"PeaknetPreprocessingPipeline\"``      batch_size: Number of events to accumulate per batch      target_height: Target image height (in pixels) after padding      target_width: Target image width (in pixels) after padding      pad_style: How to distribute padding around the image; either         ``\"center\"`` (equal padding on both sides) or ``\"bottom-right\"``         (padding added only to the bottom and right edges)         Defaults to ``\"center\"``      add_channel_dim: Whether to insert a channel dimension after batching,         converting (B, H, W) arrays to (B, C, H, W). Defaults to ``True``      num_channels: Number of channels to produce when ``add_channel_dim``         is ``True``. Defaults to ``1``
    """ # noqa: E501
    add_channel_dim: Optional[StrictBool] = True
    batch_size: StrictInt
    num_channels: Optional[StrictInt] = 1
    pad_style: Optional[StrictStr] = 'center'
    target_height: StrictInt
    target_width: StrictInt
    type: StrictStr
    __properties: ClassVar[List[str]] = ["add_channel_dim", "batch_size", "num_channels", "pad_style", "target_height", "target_width", "type"]

    @field_validator('pad_style')
    def pad_style_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['center', 'bottom-right']):
            raise ValueError("must be one of enum values ('center', 'bottom-right')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['PeaknetPreprocessingPipeline']):
            raise ValueError("must be one of enum values ('PeaknetPreprocessingPipeline')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PeaknetPreprocessingPipelineParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PeaknetPreprocessingPipelineParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "add_channel_dim": obj.get("add_channel_dim") if obj.get("add_channel_dim") is not None else True,
            "batch_size": obj.get("batch_size"),
            "num_channels": obj.get("num_channels") if obj.get("num_channels") is not None else 1,
            "pad_style": obj.get("pad_style") if obj.get("pad_style") is not None else 'center',
            "target_height": obj.get("target_height"),
            "target_width": obj.get("target_width"),
            "type": obj.get("type")
        })
        return _obj


