# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from lclstream_api_client._generated.models.psana_fields import PsanaFields
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Psana2DetectorInterfaceParameters(BaseModel):
    """
    Psana2DetectorInterfaceParameters
    """ # noqa: E501
    dtype: Optional[StrictStr] = None
    psana_fields: Optional[PsanaFields] = None
    psana_name: StrictStr
    type: StrictStr
    __properties: ClassVar[List[str]] = ["dtype", "psana_fields", "psana_name", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Psana2DetectorInterface']):
            raise ValueError("must be one of enum values ('Psana2DetectorInterface')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Psana2DetectorInterfaceParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of psana_fields
        if self.psana_fields:
            _dict['psana_fields'] = self.psana_fields.to_dict()
        # set to None if dtype (nullable) is None
        # and model_fields_set contains the field
        if self.dtype is None and "dtype" in self.model_fields_set:
            _dict['dtype'] = None

        # set to None if psana_fields (nullable) is None
        # and model_fields_set contains the field
        if self.psana_fields is None and "psana_fields" in self.model_fields_set:
            _dict['psana_fields'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Psana2DetectorInterfaceParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dtype": obj.get("dtype"),
            "psana_fields": PsanaFields.from_dict(obj["psana_fields"]) if obj.get("psana_fields") is not None else None,
            "psana_name": obj.get("psana_name"),
            "type": obj.get("type")
        })
        return _obj


