# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResourceSpec(BaseModel):
    """
    Specification of computational resources required for a job.
    """ # noqa: E501
    additional_properties: Optional[Dict[str, Any]] = None
    cpu_cores_per_process: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of CPU cores to allocate per process")
    exclusive_node_use: Optional[StrictBool] = Field(default=None, description="Whether to request exclusive use of allocated nodes")
    gpu_cores_per_process: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of GPU cores to allocate per process")
    memory: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Amount of memory to allocate in bytes")
    node_count: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of compute nodes to allocate")
    process_count: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Total number of processes to launch")
    processes_per_node: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Number of processes to launch per node")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["additional_properties", "cpu_cores_per_process", "exclusive_node_use", "gpu_cores_per_process", "memory", "node_count", "process_count", "processes_per_node"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResourceSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if cpu_cores_per_process (nullable) is None
        # and model_fields_set contains the field
        if self.cpu_cores_per_process is None and "cpu_cores_per_process" in self.model_fields_set:
            _dict['cpu_cores_per_process'] = None

        # set to None if exclusive_node_use (nullable) is None
        # and model_fields_set contains the field
        if self.exclusive_node_use is None and "exclusive_node_use" in self.model_fields_set:
            _dict['exclusive_node_use'] = None

        # set to None if gpu_cores_per_process (nullable) is None
        # and model_fields_set contains the field
        if self.gpu_cores_per_process is None and "gpu_cores_per_process" in self.model_fields_set:
            _dict['gpu_cores_per_process'] = None

        # set to None if memory (nullable) is None
        # and model_fields_set contains the field
        if self.memory is None and "memory" in self.model_fields_set:
            _dict['memory'] = None

        # set to None if node_count (nullable) is None
        # and model_fields_set contains the field
        if self.node_count is None and "node_count" in self.model_fields_set:
            _dict['node_count'] = None

        # set to None if process_count (nullable) is None
        # and model_fields_set contains the field
        if self.process_count is None and "process_count" in self.model_fields_set:
            _dict['process_count'] = None

        # set to None if processes_per_node (nullable) is None
        # and model_fields_set contains the field
        if self.processes_per_node is None and "processes_per_node" in self.model_fields_set:
            _dict['processes_per_node'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResourceSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additional_properties": obj.get("additional_properties"),
            "cpu_cores_per_process": obj.get("cpu_cores_per_process"),
            "exclusive_node_use": obj.get("exclusive_node_use"),
            "gpu_cores_per_process": obj.get("gpu_cores_per_process"),
            "memory": obj.get("memory"),
            "node_count": obj.get("node_count"),
            "process_count": obj.get("process_count"),
            "processes_per_node": obj.get("processes_per_node")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


