# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SimplonBinarySerializerParameters(BaseModel):
    """
    Configuration parameters for the Simplon binary serializer  This serializer encodes event data into the Simplon 1.8 binary message format as specified by Dectris  Attributes:      type: Discriminator field, must be ``\"SimplonBinarySerializer\"``      data_source_to_serialize: Name of the data source whose array will be         compressed and embedded in each Simplon image message      polarization_fraction: Fraction of linear polarization of the X-ray         beam (between 0 and 1)      polarization_axis: Three-element list representing the polarization         axis direction vector      data_collection_rate: Human-readable string describing the nominal         data collection rate (e.g. ``\"120 Hz\"``)      detector_name: Human-readable name of the detector      detector_type: Model or type string identifying the detector hardware
    """ # noqa: E501
    data_collection_rate: StrictStr
    data_source_to_serialize: StrictStr
    detector_name: StrictStr
    detector_type: StrictStr
    polarization_axis: List[Union[StrictFloat, StrictInt]]
    polarization_fraction: Union[StrictFloat, StrictInt]
    type: StrictStr
    __properties: ClassVar[List[str]] = ["data_collection_rate", "data_source_to_serialize", "detector_name", "detector_type", "polarization_axis", "polarization_fraction", "type"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SimplonBinarySerializer']):
            raise ValueError("must be one of enum values ('SimplonBinarySerializer')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SimplonBinarySerializerParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SimplonBinarySerializerParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_collection_rate": obj.get("data_collection_rate"),
            "data_source_to_serialize": obj.get("data_source_to_serialize"),
            "detector_name": obj.get("detector_name"),
            "detector_type": obj.get("detector_type"),
            "polarization_axis": obj.get("polarization_axis"),
            "polarization_fraction": obj.get("polarization_fraction"),
            "type": obj.get("type")
        })
        return _obj


