# coding: utf-8

"""
    LCLStream API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from lclstream_api_client._generated.models.cache_mode import CacheMode
from lclstream_api_client._generated.models.consumer_socket import ConsumerSocket
from lclstream_api_client._generated.models.job_spec import JobSpec
from lclstream_api_client._generated.models.parameters import Parameters
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TransferCreate(BaseModel):
    """
    TransferCreate
    """ # noqa: E501
    cache_mode: Optional[CacheMode] = None
    consumer_socket: Optional[ConsumerSocket] = None
    job_spec_override: Optional[JobSpec] = None
    parameters: Parameters
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cache_mode", "consumer_socket", "job_spec_override", "parameters"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TransferCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of job_spec_override
        if self.job_spec_override:
            _dict['job_spec_override'] = self.job_spec_override.to_dict()
        # override the default output from pydantic by calling `to_dict()` of parameters
        if self.parameters:
            _dict['parameters'] = self.parameters.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if job_spec_override (nullable) is None
        # and model_fields_set contains the field
        if self.job_spec_override is None and "job_spec_override" in self.model_fields_set:
            _dict['job_spec_override'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TransferCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cache_mode": obj.get("cache_mode"),
            "consumer_socket": obj.get("consumer_socket"),
            "job_spec_override": JobSpec.from_dict(obj["job_spec_override"]) if obj.get("job_spec_override") is not None else None,
            "parameters": Parameters.from_dict(obj["parameters"]) if obj.get("parameters") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


